swagger: "2.0"
info:
  version: "0.0.1"
  title: Slack Slash Integration Examples
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /reverse:
    # binds a127 app logic to a route
    x-swagger-router-controller: reverse
    post:
      description: take text and reverses it
      # used as the method name of the controller
      operationId: reverse
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: "#/parameters/token"
        - $ref: "#/parameters/command"
        - $ref: "#/parameters/text"
        - $ref: "#/parameters/team_id"
        - $ref: "#/parameters/team_domain"
        - $ref: "#/parameters/channel_id"
        - $ref: "#/parameters/channel_name"
        - $ref: "#/parameters/user_id"
        - $ref: "#/parameters/user_name"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Message"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /ticker:
    # binds a127 app logic to a route
    x-swagger-router-controller: ticker
    post:
      description: look up a stock price
      # used as the method name of the controller
      operationId: ticker
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - $ref: "#/parameters/text"
        - $ref: "#/parameters/user_name"
        - $ref: "#/parameters/icon_url"
        - $ref: "#/parameters/icon_emoji"
        - $ref: "#/parameters/channel"
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
parameters:
  token:
    name: token
    in: formData
    description: grants permission to run the command
    required: true
    type: string
  command: 
    name: command
    in: formData
    description: What command to trigger?
    required: false
    type: string
  text:
    name: text
    in: formData
    description: The argument to the command
    required: true
    type: string
  team_id:
    name: team_id
    in: formData
    description: Identifies the team context for the command
    required: false
    type: string
  team_domain:
    name: team_domain
    in: formData
    description: The Slack domain context for the command
    required: false
    type: string
  channel_id:
    name: channel_id
    in: formData
    description: "Identifies the #channel where the command was triggered"
    required: false
    type: string
  channel_name:
    name: channel_name
    in: formData
    description: "The name of the #channel where the command was triggered"
    required: false
    type: string
  user_id:
    name: user_id
    in: formData
    description: Identifies the user who issued the command
    required: false
    type: string
  user_name:
    name: user_name
    in: formData
    description: Friendly handle of the user
    required: false
    type: string
  icon_url:
    name: icon_url
    in: formData
    description: Override the bot icon
    required: false
    type: string
  icon_emoji:
    name: icon_emoji
    in: formData
    description: Override the bot icon
    required: false
    type: string
  channel:
    name: channel
    in: formData
    description: Override the bot icon
    required: false
    type: string
definitions:
  Message:
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string